In [2]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [3]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.3233, 0.3183, 0.1876, 0.4615],
        [0.0180, 0.2292, 0.1312, 0.9519],
        [0.5665, 0.1510, 0.3955, 0.4923]])
tensor([[-0.0154, -0.2189, -0.1262,  0.7543],
        [ 0.0400, -0.3032,  0.4891, -0.2260],
        [-0.2130, -0.6511,  0.6766, -0.8198]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [4]:
f = torch.full((5, 5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


In [5]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [6]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])


Original tensor:
tensor([[[ 0.2080, -1.0245,  1.9576, -1.0931, -0.1134],
         [-1.1443,  0.4999,  0.3848,  0.1718,  0.1509],
         [ 0.6686,  0.1954,  0.6090,  0.2196, -0.4171],
         [-1.3672,  1.0293,  0.8123, -1.1512, -0.3669]],

        [[ 1.4599,  0.4068,  0.3132, -0.9765, -2.4565],
         [-0.5032, -0.5447, -1.4392, -1.0745,  0.0192],
         [ 1.2841,  1.3154, -0.2170,  1.4852, -0.4032],
         [-0.2700, -1.6526,  0.9524, -0.1120,  0.7695]],

        [[-0.8958, -0.1772,  0.8348,  0.6247, -0.6672],
         [ 0.9963, -0.3931, -0.8742,  1.4569,  0.6814],
         [ 1.7862, -0.6205, -1.6108, -1.4144, -1.4865],
         [ 0.7490,  0.8509,  0.9449, -0.5351, -0.7924]]])

Tensor a[1]:
tensor([[ 1.4599,  0.4068,  0.3132, -0.9765, -2.4565],
        [-0.5032, -0.5447, -1.4392, -1.0745,  0.0192],
        [ 1.2841,  1.3154, -0.2170,  1.4852, -0.4032],
        [-0.2700, -1.6526,  0.9524, -0.1120,  0.7695]])

Tensor a[1:, 2:4]:
tensor([[[ 1.2841,  1.3154, -0.2170,  1.4852, -0.4

In [7]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.8007, -0.8806,  0.6006,  1.0358],
        [-1.2901,  1.5877, -1.0678, -0.9052],
        [-0.9854, -0.0748, -0.2465,  0.5439]])

Flatten:
tensor([ 0.8007, -0.8806,  0.6006,  1.0358, -1.2901,  1.5877, -1.0678, -0.9052,
        -0.9854, -0.0748, -0.2465,  0.5439])

Reshape to 3 x 2 x 2:
tensor([[[ 0.8007, -0.8806],
         [ 0.6006,  1.0358]],

        [[-1.2901,  1.5877],
         [-1.0678, -0.9052]],

        [[-0.9854, -0.0748],
         [-0.2465,  0.5439]]])


In [8]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 1.3775,  1.0105,  0.3723],
        [ 0.6818, -0.3371,  0.3104]])
b:
tensor([[ 0.6834, -0.4475, -0.7791],
        [-0.9727, -1.2217,  0.6744]])

a + b:
tensor([[ 2.0609,  0.5630, -0.4068],
        [-0.2909, -1.5588,  0.9848]])

a / b:
tensor([[ 2.0157, -2.2582, -0.4779],
        [-0.7010,  0.2759,  0.4603]])

a^2:
tensor([[1.8975, 1.0212, 0.1386],
        [0.4648, 0.1136, 0.0964]])

Matrix multiplication:
tensor([[ 0.1991, -2.3233],
        [ 0.3749, -0.0419]])


In [9]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.3494, -1.0958, -0.5968,  0.7872],
        [ 1.5843,  0.2122, -0.3399, -0.6001],
        [ 1.5061, -1.4338,  4.0382,  1.7020]])

Mean:
tensor([ 1.1466, -0.7725,  1.0338,  0.6297])

Standard deviation:
tensor([0.6915, 0.8693, 2.6050, 1.1591])

Cumulative sum:
tensor([[ 0.3494, -1.0958, -0.5968,  0.7872],
        [ 1.9337, -0.8836, -0.9367,  0.1871],
        [ 3.4398, -2.3175,  3.1014,  1.8891]])


In [10]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [12]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.1965],
        [0.5146],
        [1.5307]], requires_grad=True)
Learned coefficients:
tensor([[1.0125],
        [1.8797],
        [2.7288]], requires_grad=True)


In [14]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.3428, requires_grad=True)
B = tensor(4.6571, requires_grad=True)
C = tensor(3.6572, requires_grad=True)
D = tensor(2.6571, requires_grad=True)


In [15]:
import torch
import numpy as np

# =========================
# 1. Tạo Tensor X có 24 phần tử
# =========================

X = torch.arange(1, 25)

print("X ban đầu:")
print(X)

print("\nX reshape 4 x 6:")
print(X.reshape(4, 6))

print("\nX reshape 2 x 12:")
print(X.reshape(2, 12))

print("\nX reshape 2 x 3 x 4:")
print(X.reshape(2, 3, 4))


# =========================
# 2. Tensor A, B kích thước 3 x 4
# =========================

A = torch.randn(3, 4)
B = torch.randn(3, 4)

print("\nA:")
print(A)

print("\nB:")
print(B)

print("\nA + B:")
print(A + B)

print("\nA * B:")
print(A * B)

print("\nA / B:")
print(A / B)

print("\nTrung bình theo cột:")
print(torch.mean(A, dim=0))

print("\nĐộ lệch chuẩn theo cột:")
print(torch.std(A, dim=0))


# =========================
# 3. Tính đạo hàm bằng autograd
# y = 2x^2 + 5x + 3
# =========================

x = torch.tensor(2.0, requires_grad=True)

y = 2 * x**2 + 5 * x + 3

y.backward()

print("\nx =", x)
print("y =", y)
print("dy/dx =", x.grad)

# Tính thủ công:
# y' = 4x + 5
# tại x = 2:
# y' = 4*2 + 5 = 13


# =========================
# 4. Huấn luyện đa thức
# y = 2x^2 - 3x + 5
# =========================

polynomial = np.poly1d([2, -3, 5])

N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True)

x_data = torch.tensor(XX, dtype=torch.float32)
y_data = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()

    y_pred = x_data @ w

    mse = torch.mean(torch.square(y_data - y_pred))

    mse.backward()

    optimizer.step()

print("\nCác hệ số tìm được:")
print(w)

X ban đầu:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])

X reshape 4 x 6:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

X reshape 2 x 12:
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

X reshape 2 x 3 x 4:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

A:
tensor([[ 0.7700, -0.5490,  0.7485, -0.8907],
        [-0.3349,  0.6655,  2.1174, -0.8908],
        [-0.0291, -1.1398, -1.2027, -0.2887]])

B:
tensor([[-1.2401, -1.1545, -0.8732, -0.5999],
        [ 1.2126, -0.2085, -0.3504, -0.7906],
        [ 0.5252, -0.2573,  1.3810, -0.7834]])

A + B:
tensor([[-0.4701, -1.7035, -0.1246, -1.4907],
        [ 0.8777,  0.4570,  1.7670, -1.6814],
        [ 0